services:
  - type: web
    name: sistema-academia
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python -m flask --app app init-db && gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: PUBLIC_BASE_URL
        value: https://sistema-de-academia.onrender.com
      - key: RESEND_API_KEY
        sync: false
      - key: SMTP_FROM
        sync: false
